// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clevertechware/concevoir-une-api-paginee-golang/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type Logger
func (_mock *Logger) Debug(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type Logger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) Debug(msg any, args ...any) *Logger_Debug_Call {
	return &Logger_Debug_Call{Call: _e.mock.On("Debug",
		append([]any{msg}, args...)...)}
}

func (_c *Logger_Debug_Call) Run(run func(msg string, args ...any)) *Logger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Debug_Call) Return() *Logger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Debug_Call) RunAndReturn(run func(msg string, args ...any)) *Logger_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugContext provides a mock function for the type Logger
func (_mock *Logger) DebugContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type Logger_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) DebugContext(ctx any, msg any, args ...any) *Logger_DebugContext_Call {
	return &Logger_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]any{ctx, msg}, args...)...)}
}

func (_c *Logger_DebugContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_DebugContext_Call) Return() *Logger_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_DebugContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_DebugContext_Call {
	_c.Run(run)
	return _c
}

// Enabled provides a mock function for the type Logger
func (_mock *Logger) Enabled(level logger.Level) bool {
	ret := _mock.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(logger.Level) bool); ok {
		r0 = returnFunc(level)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Logger_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type Logger_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - level logger.Level
func (_e *Logger_Expecter) Enabled(level any) *Logger_Enabled_Call {
	return &Logger_Enabled_Call{Call: _e.mock.On("Enabled", level)}
}

func (_c *Logger_Enabled_Call) Run(run func(level logger.Level)) *Logger_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Level
		if args[0] != nil {
			arg0 = args[0].(logger.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_Enabled_Call) Return(b bool) *Logger_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Logger_Enabled_Call) RunAndReturn(run func(level logger.Level) bool) *Logger_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type Logger
func (_mock *Logger) Error(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Logger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) Error(msg any, args ...any) *Logger_Error_Call {
	return &Logger_Error_Call{Call: _e.mock.On("Error",
		append([]any{msg}, args...)...)}
}

func (_c *Logger_Error_Call) Run(run func(msg string, args ...any)) *Logger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Error_Call) Return() *Logger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Error_Call) RunAndReturn(run func(msg string, args ...any)) *Logger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type Logger
func (_mock *Logger) ErrorContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type Logger_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) ErrorContext(ctx any, msg any, args ...any) *Logger_ErrorContext_Call {
	return &Logger_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]any{ctx, msg}, args...)...)}
}

func (_c *Logger_ErrorContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_ErrorContext_Call) Return() *Logger_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type Logger
func (_mock *Logger) Info(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Logger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) Info(msg any, args ...any) *Logger_Info_Call {
	return &Logger_Info_Call{Call: _e.mock.On("Info",
		append([]any{msg}, args...)...)}
}

func (_c *Logger_Info_Call) Run(run func(msg string, args ...any)) *Logger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Info_Call) Return() *Logger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Info_Call) RunAndReturn(run func(msg string, args ...any)) *Logger_Info_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type Logger
func (_mock *Logger) InfoContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type Logger_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) InfoContext(ctx any, msg any, args ...any) *Logger_InfoContext_Call {
	return &Logger_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]any{ctx, msg}, args...)...)}
}

func (_c *Logger_InfoContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_InfoContext_Call) Return() *Logger_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_InfoContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_InfoContext_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type Logger
func (_mock *Logger) Warn(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type Logger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) Warn(msg any, args ...any) *Logger_Warn_Call {
	return &Logger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, args...)...)}
}

func (_c *Logger_Warn_Call) Run(run func(msg string, args ...any)) *Logger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Warn_Call) Return() *Logger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Warn_Call) RunAndReturn(run func(msg string, args ...any)) *Logger_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type Logger
func (_mock *Logger) WarnContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type Logger_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) WarnContext(ctx any, msg any, args ...any) *Logger_WarnContext_Call {
	return &Logger_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]any{ctx, msg}, args...)...)}
}

func (_c *Logger_WarnContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_WarnContext_Call) Return() *Logger_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_WarnContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_WarnContext_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type Logger
func (_mock *Logger) With(args ...any) logger.Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(...any) logger.Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// Logger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type Logger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...any
func (_e *Logger_Expecter) With(args ...any) *Logger_With_Call {
	return &Logger_With_Call{Call: _e.mock.On("With",
		append([]any{}, args...)...)}
}

func (_c *Logger_With_Call) Run(run func(args ...any)) *Logger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Logger_With_Call) Return(logger1 logger.Logger) *Logger_With_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *Logger_With_Call) RunAndReturn(run func(args ...any) logger.Logger) *Logger_With_Call {
	_c.Call.Return(run)
	return _c
}
