// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clevertechware/concevoir-une-api-paginee-golang/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionService is an autogenerated mock type for the transactionService type
type TransactionService struct {
	mock.Mock
}

type TransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionService) EXPECT() *TransactionService_Expecter {
	return &TransactionService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type TransactionService
func (_mock *TransactionService) List(ctx context.Context, q domain.ListQuery, limit int, token string) (domain.KeysetPage, error) {
	ret := _mock.Called(ctx, q, limit, token)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.KeysetPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, int, string) (domain.KeysetPage, error)); ok {
		return returnFunc(ctx, q, limit, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, int, string) domain.KeysetPage); ok {
		r0 = returnFunc(ctx, q, limit, token)
	} else {
		r0 = ret.Get(0).(domain.KeysetPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListQuery, int, string) error); ok {
		r1 = returnFunc(ctx, q, limit, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TransactionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q domain.ListQuery
//   - limit int
//   - token string
func (_e *TransactionService_Expecter) List(ctx any, q any, limit any, token any) *TransactionService_List_Call {
	return &TransactionService_List_Call{Call: _e.mock.On("List", ctx, q, limit, token)}
}

func (_c *TransactionService_List_Call) Run(run func(ctx context.Context, q domain.ListQuery, limit int, token string)) *TransactionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListQuery
		if args[1] != nil {
			arg1 = args[1].(domain.ListQuery)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TransactionService_List_Call) Return(keysetPage domain.KeysetPage, err error) *TransactionService_List_Call {
	_c.Call.Return(keysetPage, err)
	return _c
}

func (_c *TransactionService_List_Call) RunAndReturn(run func(ctx context.Context, q domain.ListQuery, limit int, token string) (domain.KeysetPage, error)) *TransactionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOffset provides a mock function for the type TransactionService
func (_mock *TransactionService) ListByOffset(ctx context.Context, accountID int64, page int, size int) (domain.OffsetPage, error) {
	ret := _mock.Called(ctx, accountID, page, size)

	if len(ret) == 0 {
		panic("no return value specified for ListByOffset")
	}

	var r0 domain.OffsetPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) (domain.OffsetPage, error)); ok {
		return returnFunc(ctx, accountID, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) domain.OffsetPage); ok {
		r0 = returnFunc(ctx, accountID, page, size)
	} else {
		r0 = ret.Get(0).(domain.OffsetPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = returnFunc(ctx, accountID, page, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionService_ListByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOffset'
type TransactionService_ListByOffset_Call struct {
	*mock.Call
}

// ListByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - page int
//   - size int
func (_e *TransactionService_Expecter) ListByOffset(ctx any, accountID any, page any, size any) *TransactionService_ListByOffset_Call {
	return &TransactionService_ListByOffset_Call{Call: _e.mock.On("ListByOffset", ctx, accountID, page, size)}
}

func (_c *TransactionService_ListByOffset_Call) Run(run func(ctx context.Context, accountID int64, page int, size int)) *TransactionService_ListByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TransactionService_ListByOffset_Call) Return(offsetPage domain.OffsetPage, err error) *TransactionService_ListByOffset_Call {
	_c.Call.Return(offsetPage, err)
	return _c
}

func (_c *TransactionService_ListByOffset_Call) RunAndReturn(run func(ctx context.Context, accountID int64, page int, size int) (domain.OffsetPage, error)) *TransactionService_ListByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Total provides a mock function for the type TransactionService
func (_mock *TransactionService) Total(ctx context.Context, exact bool) (int64, error) {
	ret := _mock.Called(ctx, exact)

	if len(ret) == 0 {
		panic("no return value specified for Total")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (int64, error)); ok {
		return returnFunc(ctx, exact)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) int64); ok {
		r0 = returnFunc(ctx, exact)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, exact)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionService_Total_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Total'
type TransactionService_Total_Call struct {
	*mock.Call
}

// Total is a helper method to define mock.On call
//   - ctx context.Context
//   - exact bool
func (_e *TransactionService_Expecter) Total(ctx any, exact any) *TransactionService_Total_Call {
	return &TransactionService_Total_Call{Call: _e.mock.On("Total", ctx, exact)}
}

func (_c *TransactionService_Total_Call) Run(run func(ctx context.Context, exact bool)) *TransactionService_Total_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionService_Total_Call) Return(n int64, err error) *TransactionService_Total_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TransactionService_Total_Call) RunAndReturn(run func(ctx context.Context, exact bool) (int64, error)) *TransactionService_Total_Call {
	_c.Call.Return(run)
	return _c
}
