// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clevertechware/concevoir-une-api-paginee-golang/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionRepository is an autogenerated mock type for the transactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// CountEstimate provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) CountEstimate(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountEstimate")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_CountEstimate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEstimate'
type TransactionRepository_CountEstimate_Call struct {
	*mock.Call
}

// CountEstimate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TransactionRepository_Expecter) CountEstimate(ctx any) *TransactionRepository_CountEstimate_Call {
	return &TransactionRepository_CountEstimate_Call{Call: _e.mock.On("CountEstimate", ctx)}
}

func (_c *TransactionRepository_CountEstimate_Call) Run(run func(ctx context.Context)) *TransactionRepository_CountEstimate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TransactionRepository_CountEstimate_Call) Return(n int64, err error) *TransactionRepository_CountEstimate_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TransactionRepository_CountEstimate_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *TransactionRepository_CountEstimate_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) Export(ctx context.Context, afterID int64, limit int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, afterID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type TransactionRepository_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID int64
//   - limit int
func (_e *TransactionRepository_Expecter) Export(ctx any, afterID any, limit any) *TransactionRepository_Export_Call {
	return &TransactionRepository_Export_Call{Call: _e.mock.On("Export", ctx, afterID, limit)}
}

func (_c *TransactionRepository_Export_Call) Run(run func(ctx context.Context, afterID int64, limit int)) *TransactionRepository_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_Export_Call) Return(transactions []domain.Transaction, err error) *TransactionRepository_Export_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *TransactionRepository_Export_Call) RunAndReturn(run func(ctx context.Context, afterID int64, limit int) ([]domain.Transaction, error)) *TransactionRepository_Export_Call {
	_c.Call.Return(run)
	return _c
}

// FirstPage provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) FirstPage(ctx context.Context, q domain.ListQuery, limit int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, q, limit)

	if len(ret) == 0 {
		panic("no return value specified for FirstPage")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, q, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, q, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListQuery, int) error); ok {
		r1 = returnFunc(ctx, q, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_FirstPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstPage'
type TransactionRepository_FirstPage_Call struct {
	*mock.Call
}

// FirstPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q domain.ListQuery
//   - limit int
func (_e *TransactionRepository_Expecter) FirstPage(ctx any, q any, limit any) *TransactionRepository_FirstPage_Call {
	return &TransactionRepository_FirstPage_Call{Call: _e.mock.On("FirstPage", ctx, q, limit)}
}

func (_c *TransactionRepository_FirstPage_Call) Run(run func(ctx context.Context, q domain.ListQuery, limit int)) *TransactionRepository_FirstPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListQuery
		if args[1] != nil {
			arg1 = args[1].(domain.ListQuery)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_FirstPage_Call) Return(transactions []domain.Transaction, err error) *TransactionRepository_FirstPage_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *TransactionRepository_FirstPage_Call) RunAndReturn(run func(ctx context.Context, q domain.ListQuery, limit int) ([]domain.Transaction, error)) *TransactionRepository_FirstPage_Call {
	_c.Call.Return(run)
	return _c
}

// NextPage provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) NextPage(ctx context.Context, q domain.ListQuery, after domain.Bound, limit int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, q, after, limit)

	if len(ret) == 0 {
		panic("no return value specified for NextPage")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, domain.Bound, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, q, after, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListQuery, domain.Bound, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, q, after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListQuery, domain.Bound, int) error); ok {
		r1 = returnFunc(ctx, q, after, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_NextPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextPage'
type TransactionRepository_NextPage_Call struct {
	*mock.Call
}

// NextPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q domain.ListQuery
//   - after domain.Bound
//   - limit int
func (_e *TransactionRepository_Expecter) NextPage(ctx any, q any, after any, limit any) *TransactionRepository_NextPage_Call {
	return &TransactionRepository_NextPage_Call{Call: _e.mock.On("NextPage", ctx, q, after, limit)}
}

func (_c *TransactionRepository_NextPage_Call) Run(run func(ctx context.Context, q domain.ListQuery, after domain.Bound, limit int)) *TransactionRepository_NextPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListQuery
		if args[1] != nil {
			arg1 = args[1].(domain.ListQuery)
		}
		var arg2 domain.Bound
		if args[2] != nil {
			arg2 = args[2].(domain.Bound)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TransactionRepository_NextPage_Call) Return(transactions []domain.Transaction, err error) *TransactionRepository_NextPage_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *TransactionRepository_NextPage_Call) RunAndReturn(run func(ctx context.Context, q domain.ListQuery, after domain.Bound, limit int) ([]domain.Transaction, error)) *TransactionRepository_NextPage_Call {
	_c.Call.Return(run)
	return _c
}

// OffsetPage provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) OffsetPage(ctx context.Context, accountID int64, offset int, limit int) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, accountID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for OffsetPage")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, accountID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) []domain.Transaction); ok {
		r0 = returnFunc(ctx, accountID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = returnFunc(ctx, accountID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_OffsetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OffsetPage'
type TransactionRepository_OffsetPage_Call struct {
	*mock.Call
}

// OffsetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - offset int
//   - limit int
func (_e *TransactionRepository_Expecter) OffsetPage(ctx any, accountID any, offset any, limit any) *TransactionRepository_OffsetPage_Call {
	return &TransactionRepository_OffsetPage_Call{Call: _e.mock.On("OffsetPage", ctx, accountID, offset, limit)}
}

func (_c *TransactionRepository_OffsetPage_Call) Run(run func(ctx context.Context, accountID int64, offset int, limit int)) *TransactionRepository_OffsetPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TransactionRepository_OffsetPage_Call) Return(transactions []domain.Transaction, err error) *TransactionRepository_OffsetPage_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *TransactionRepository_OffsetPage_Call) RunAndReturn(run func(ctx context.Context, accountID int64, offset int, limit int) ([]domain.Transaction, error)) *TransactionRepository_OffsetPage_Call {
	_c.Call.Return(run)
	return _c
}
